# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 685ce582b27aafeb2d6d1aedcbd82c603d7ee4adc50ee1020a25a4595748882a5f55b678de5aba9227a20c04acc21c6484785102ebf59d88bb710a0c21c7de96

test:
  secret_key_base: 66a248cdfc61865184b7b8ffb552270519b809dab1f7acdf73195d7bf29a48e33b7b449e65ed0f76c0ea6ccae5f69734eb2f6ea009922082f020c88dc4960658

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
