source "https://rubygems.org"

gem "rails", "4.2.1"
gem "rake", "~> 11.1.2"
gem "sdoc", "~> 0.4.0", group: :doc
gem "pg", "0.19.0"
gem "sidekiq"
gem "sidekiq-status"


group :development, :test do
  gem "rspec-rails", "~> 3.5"
end

